Edit readme - playbook must be run from CM server
cloudera/cloudera-playbook pull request #9
Opened 2017-11-29 17:34 UTC by alexbleakley

Playbook must be run from the host designated as the CM server, else the user will run into issues with cm-api not being installed in the right place. Amended readme to add this info and to make clear that all steps must be taken from that same host.

2019-05-06 14:17 UTC, lhoss commented
> else the user will run into issues with cm-api not being installed in the right place
Is this limitation still valid?
If yes, let's merge this PR 👍

2019-05-08 13:40 UTC, lhoss requested changes

2019-05-08 13:40 UTC, lhoss commented on README.md
> +* Setup an [Ansible Control Machine](http://docs.ansible.com/ansible/intro_installation.html)
I'ld add 1 line here:
  * Install the cm-api python module on the Control Machine, if it differs from the scm_server host, using `pip install cm-api`

With that, you can get rid of the constraint documented below in lines 66-67
(see also my comment in the PR overview)

2019-05-24 18:35 UTC, roczei commented
Hi @alexbleakley,

You need to first sign and return an ICLA and CCLA before we can accept and redistribute your contribution. Once these are submitted you are free to start contributing to cloudera-playbook. Submit these to CLA@cloudera.com

Here you can find the pdf files:

https://github.com/cloudera/cloudera-playbook/tree/master/icla

Please update this issue (9) if you receive the confirmation from our CLA team.

Thank you!

2019-08-27 09:53 UTC, dbeech commented
Closing this PR in favour of alternative solution proposed by @lhoss in comments. Will open separate issue/PR for this soon.

2019-08-27 09:53 UTC, closed without merging